version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=task_db
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=password
    ports:
      - '5412:5432'
